let firstNumber = 1;
let secondNumber = 2;
let thirdNumber = 4;
let fourthNumber = 8;
console.log(firstNumber * secondNumber);
console.log(secondNumber * secondNumber);
console.log(firstNumber * fourthNumber);
console.log(thirdNumber * thirdNumber);
let fifthNumber = 6;
let sixthNumber = 356;
let seventhNumber = 130;
let eighthNumber = 196;
let ninthNumber = 246;
console.log(fifthNumber / secondNumber);
console.log(sixthNumber / secondNumber);
console.log(seventhNumber / secondNumber);
console.log(eighthNumber / secondNumber);
console.log(ninthNumber / secondNumber);
const prix = 79.99;
let rate = 0.19;
let newSolde = 15.1981;
let prixInitial = 79.99;
console.log(prix * rate);
console.log(prixInitial - newSolde);
